services:
  frontend:
    build:
     context: ./TreeSpotter_Frontend/tree-spotter-frontend
     dockerfile: Dockerfile.prod
    depends_on:
      - backend
    ports:
      - 127.0.0.1:4200:4200
    networks:
      - frontend

  backend:
    build:
      context: ./TreeSpotter_Backend
      dockerfile: Dockerfile.prod
    env_file:
      - env/backend.prod.env
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - backend
      - frontend
  
  migrate:
    image: migrate/migrate
    entrypoint: ["/migrate.sh"]
    volumes:
      - ./migrations:/migrations
      - ./migrate.sh:/migrate.sh
    env_file:
      - env/migrate.prod.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

  database:
    image: mysql
    restart: always
    env_file:
      - env/database.prod.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mysql_data: